name: POSIX

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - feature/**

env:
  UBSAN_OPTIONS: print_stacktrace=1
  B2_VARIANT: debug,release
  B2_LINK: shared,static

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: g++-4.4,        cxxstd: '98,0x',                         os: ubuntu-16.04, install: g++-4.4 }
          - { compiler: g++-9,          cxxstd: '03,11,14,17,2a', sanitize: yes, os: ubuntu-20.04, install: g++-9, linkflags: -fuse-ld=gold }
          - { compiler: clang++-3.5,    cxxstd: '03,11',                         os: ubuntu-16.04, install: clang-3.5 }
          - { compiler: clang++-10,     cxxstd: '03,11,14,17,2a', sanitize: yes, os: ubuntu-20.04, install: clang-10 }
          - { compiler: clang++-libc++, cxxstd: '03,11,14',                      os: ubuntu-18.04, install: 'libc++-dev libc++-helpers' }
          - { compiler: clang++,        cxxstd: '03,11,14,1z',    sanitize: yes, os: macos-10.15 }
          # Codecov
          - { compiler: g++-8,          cxxstd: '03,11',          coverage: yes, os: ubuntu-20.04, install: g++-8 }

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        if: matrix.install
        run: sudo apt install ${{matrix.install}}

      - name: Setup config vars
        run: |
          echo ::set-env name=LIBRARY::${GITHUB_REPOSITORY#*/}
          echo ::set-env name=B2_COMPILER::${{matrix.compiler}}
          ${{matrix.compiler}} --version
          if [[ "${{matrix.compiler}}" =~ clang ]]; then
              B2_TOOLSET=clang
          elif [[ "${{matrix.compiler}}" =~ g\+\+ ]]; then
              B2_TOOLSET=gcc
          else
              echo "Unknown compiler: ${{matrix.compiler}}" >&2
              false
          fi
          echo "using $B2_TOOLSET : : ${{matrix.compiler}} ;" > ~/user-config.jam
          echo ::set-env name=B2_TOOLSET::$B2_TOOLSET
          echo ::set-env name=B2_CXXSTD::${{matrix.cxxstd}}
          if [[ "${{matrix.sanitize}}" == "yes" ]]; then 
            echo ::set-env name=B2_ASAN::address-sanitizer=norecover
            echo ::set-env name=B2_UBSAN::undefined-sanitizer=norecover
          fi
          [[ "${{matrix.linkflags}}" == "" ]] || echo ::set-env name=B2_LINKFLAGS::linkflags=${{matrix.linkflags}}

      - name: Setup Boost
        run: |
          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
          BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
          cd ..
          git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
          git submodule update --init tools/boostdep
          python tools/boostdep/depinst/depinst.py --git_args "--jobs 3" $LIBRARY
          ./bootstrap.sh
          ./b2 headers

      - name: Setup coverage
        if: matrix.coverage
        run: .github/codecov.sh setup

      - name: Run tests
        working-directory: ${{github.workspace}}/../boost-root
        run: ./b2 -j3 libs/$LIBRARY/test toolset=$B2_TOOLSET cxxstd=$B2_CXXSTD variant=$B2_VARIANT link=$B2_LINK $B2_ASAN $B2_UBSAN $B2_LINKFLAGS $B2_FLAGS

      - name: Collect coverage
        if: matrix.coverage
        working-directory: ${{github.workspace}}/../boost-root
        run: ${{github.workspace}}/.github/codecov.sh collect
